import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useNavigate } from "react-router";
import { Sparkles, Utensils, Zap, Save } from "lucide-react";

export default function Landing() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-yellow-50 to-green-50 dark:from-orange-950 dark:via-yellow-950 dark:to-green-950">
      {/* Hero Section */}
      <div className="container mx-auto px-4 py-16">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center max-w-4xl mx-auto"
        >
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ delay: 0.2, type: "spring", stiffness: 200 }}
            className="text-8xl mb-6"
          >
            🍳
          </motion.div>
          
          <h1 className="text-6xl md:text-7xl font-bold tracking-tight mb-6 bg-gradient-to-r from-orange-600 via-yellow-600 to-green-600 bg-clip-text text-transparent">
            FoodCraft
          </h1>
          
          <p className="text-xl md:text-2xl text-muted-foreground mb-8 max-w-2xl mx-auto">
            Combine ingredients to discover amazing new dishes! Start with the basic elements and create your culinary universe.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button
              size="lg"
              className="text-lg px-8 py-6"
              onClick={() => navigate("/game")}
            >
              <Sparkles className="mr-2 w-5 h-5" />
              Start Cooking
            </Button>
            <Button
              size="lg"
              variant="outline"
              className="text-lg px-8 py-6"
              onClick={() => {
                const gameId = prompt("Enter your game code:");
                if (gameId) navigate(`/game?load=${gameId}`);
              }}
            >
              <Save className="mr-2 w-5 h-5" />
              Load Game
            </Button>
          </div>
        </motion.div>

        {/* Features */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4, duration: 0.6 }}
          className="grid md:grid-cols-3 gap-6 mt-20 max-w-5xl mx-auto"
        >
          <Card className="border-2 hover:shadow-lg transition-all">
            <CardHeader>
              <div className="text-4xl mb-2">🎨</div>
              <CardTitle>AI-Powered</CardTitle>
              <CardDescription>
                Discover unique dishes generated by AI with creative names and beautiful images
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="border-2 hover:shadow-lg transition-all">
            <CardHeader>
              <div className="text-4xl mb-2">💾</div>
              <CardTitle>Save & Share</CardTitle>
              <CardDescription>
                Get a unique game code to save your progress and continue anytime, anywhere
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="border-2 hover:shadow-lg transition-all">
            <CardHeader>
              <div className="text-4xl mb-2">♾️</div>
              <CardTitle>Endless Combos</CardTitle>
              <CardDescription>
                Millions of possible combinations waiting to be discovered. How many can you find?
              </CardDescription>
            </CardHeader>
          </Card>
        </motion.div>

        {/* How to Play */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6, duration: 0.6 }}
          className="mt-20 max-w-3xl mx-auto"
        >
          <h2 className="text-3xl font-bold text-center mb-8">How to Play</h2>
          <div className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-3">
                  <span className="bg-primary text-primary-foreground w-8 h-8 rounded-full flex items-center justify-center font-bold">1</span>
                  Start with the basics
                </CardTitle>
                <CardDescription>
                  Begin with Water 💧, Fire 🔥, Earth 🌍, and Air 💨
                </CardDescription>
              </CardHeader>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-3">
                  <span className="bg-primary text-primary-foreground w-8 h-8 rounded-full flex items-center justify-center font-bold">2</span>
                  Drag and combine
                </CardTitle>
                <CardDescription>
                  Drag two ingredients into the combine zone to create something new
                </CardDescription>
              </CardHeader>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-3">
                  <span className="bg-primary text-primary-foreground w-8 h-8 rounded-full flex items-center justify-center font-bold">3</span>
                  Discover and expand
                </CardTitle>
                <CardDescription>
                  Use your discoveries to create even more complex dishes and ingredients
                </CardDescription>
              </CardHeader>
            </Card>
          </div>
        </motion.div>

        {/* Footer */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8, duration: 0.6 }}
          className="text-center mt-20 text-sm text-muted-foreground"
        >
          <p>Powered by AI • Games auto-delete after 30 days of inactivity</p>
        </motion.div>
      </div>
    </div>
  );
}